services:
  # Seu backend (sem alteração)
  backend:
    build: .
    container_name: moments-backend
    env_file:
      - .env
    networks:
      - app-network

  # Seu Nginx (sem alteração)
  nginx:
    image: nginx:latest
    container_name: floripa-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-network

  # Novo serviço para o Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Acesso ao Prometheus em http://<EC2_IP>:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  # Novo serviço para o Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Acesso ao Grafana em http://<EC2_IP>:3000
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge